/* Generated by assets/make_burst.py -- DO NOT EDIT BY HAND. */
#ifndef BURST_IMG_H
#define BURST_IMG_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_BUILD_TEST)
#include "../lvgl.h"
#else
#include <lvgl.h>
#endif

/* 30x30, LV_IMG_CF_TRUE_COLOR_ALPHA, 2700 bytes of flash.
 *
 *   lv_obj_t *img = lv_img_create(parent);
 *   lv_img_set_src(img, &burst_img);
 */
extern const lv_img_dsc_t burst_img;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* BURST_IMG_H */
